name: Publish
on:
  workflow_dispatch:

jobs:
  publish:
    name: publish
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@master

    - name: setup docs
      run: |
        mkdir -p docs
        touch docs/.nojekyll

    - name: setup node
      uses: actions/setup-node@v4
      with:
        node-version: 20
        cache: "npm"
        cache-dependency-path: ./vis/package-lock.json

    - name: dependencias
      working-directory: ./vis
      run: npm ci

    - name: build
      working-directory: ./vis
      run: npm run build

    - name: publicar
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./docs